on:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          allow_issue_writing: false
          target: 'https://devopsedu.vn/'
